# _config.yml

# Basic settings
title: Amalanku - Aplikasi Amalan Islam Sehari-hari
description: Amalanku adalah aplikasi mobile yang dirancang khusus untuk membantu umat Islam melacak dan mengelola amalan harian kamu.
theme: jekyll-theme-cayman
show_downloads: false

# Site metadata
url: "https://amalanku.github.io"
author: "FlagoDNA Developer Labs"
